# Generated by Django 5.1.2 on 2024-10-27 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_options_remove_user_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 6, 30, 55, 27324, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
