# Generated by Django 5.1.2 on 2024-10-27 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_account_creation_date_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 6, 33, 12, 696922, tzinfo=datetime.timezone.utc)),
        ),
    ]
