# Generated by Django 5.1.2 on 2024-10-27 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_account_creation_date_alter_user_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 7, 5, 9, 103238, tzinfo=datetime.timezone.utc)),
        ),
    ]
