# Generated by Django 5.1.2 on 2024-10-27 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_lastname_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 13, 18, 26, 20152, tzinfo=datetime.timezone.utc)),
        ),
    ]
